### ISSUE TITLE
Sync exits with error for the past 4 days.

### ISSUE THREAD

**Issue by demongokul** [scotthartbti/android#12]
Hi, i have been getting the same error: Exited sync due to fetch errors for the past 4 days. Should i wait more to start syncing Beanstalk again? I have tried --force-sync and -f as arguments too.

**Comment by scotthartbti** [comment]
You need to find exactly what is failing.  Chances are that you need to
force sync to overwrite something.  I sync nightly and everything's working
as it should.  Try repo sync --force-sync and see if that helps.  If not, u
need to find exactly what is failing.. It should tell you, u just need to
look.
